import { z } from 'zod'

export const accountSchema = z.object({
  companyName: z.string(),
  companyFantasyName: z.string(),
  companyDocument: z.string(),
  companyDateCreated: z
    .string()
    .regex(/^\d{2}\/\d{2}\/\d{4}$/, 'Data inválida, use o formato DD/MM/AAAA'),
  companyEmailAddress: z.string(),
  companyPhoneNumber: z.string(),
  companyPhoneNumber2: z.string().optional(),
  companyAddress: z.string(),
  companyAddressNumber: z.string(),
  companyAddressComplement: z.string(),
  companyNeighborhood: z.string(),
  companyCity: z.string(),
  companyState: z.string(),
  companyCodezip: z.string(),
  ownerName: z.string(),
  ownerDocument: z.string(),
  ownerMotherName: z.string(),
  ownerEmailAddress: z.string(),
  ownerBirthday: z
    .string()
    .regex(/^\d{2}\/\d{2}\/\d{4}$/, 'Data inválida, use o formato DD/MM/AAAA'),
  ownerPhoneNumber: z.string(),
  ownerPhoneNumber2: z.string().optional(),
  ownerAddress: z.string(),
  ownerAddressNumber: z.string(),
  ownerAddressComplement: z.string(),
  ownerNeighborhood: z.string(),
  ownerCity: z.string(),
  ownerState: z.string(),
  ownerCodezip: z.string(),
  imgSelfie: z.string(),
  imgRgFront: z.string(),
  imgRgBack: z.string(),
  latitude:    z.number(),
  longitude:   z.number(),
  city:        z.string(),
  state:       z.string(),
  contry:      z.string(),
  zipCode:     z.string(),
  createdAT:   z.string(),
  time:        z.string(),
  ip:          z.string(),   
  idDevice:    z.string(),
})
